on:
  schedule:
    - cron: "0 * * * *" # Run every hour

jobs:
  send_mail:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout git mpg123 clone"
        uses: "actions/checkout@v2"
        with:
          ref: "updater"
      - name: "Setup python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.x"
      - name: "Install Python requirements"
        run: |
          python -m pip install --user markdown pygithub
      - name: "Send mail"
        run: |
          python scripts/mail-for-all-new-open-prs.py
